
airlines = {'UA': 'United Airlines',
            'AS': 'Alaska Airlines',
            '9E': 'Endeavor Air',
            'B6': 'JetBlue Airways',
            'EV': 'ExpressJet',
            'F9': 'Frontier Airlines',
            'G4': 'Allegiant Air',
            'HA': 'Hawaiian Airlines',
            'MQ': 'Envoy Air',
            'NK': 'Spirit Airlines',
            'OH': 'PSA Airlines',
            'OO': 'SkyWest Airlines',
            'VX': 'Virgin America',
            'WN': 'Southwest Airlines',
            'YV': 'Mesa Airline',
            'YX': 'Republic Airways',
            'AA': 'American Airlines',
            'DL': 'Delta Airlines'}

data = {'United Airlines': 621565, 'Alaska Airlines': 245761, 'Endeavor Air': 245917,
        'JetBlue Airways': 305010, 'ExpressJet': 202890, 'Frontier Airlines': 120035,
        'Allegiant Air': 96221, 'Hawaiian Airlines': 83723, 'Envoy Air': 296001,
        'Spirit Airlines': 176178, 'PSA Airlines': 278457, 'SkyWest Airlines': 774137,
        'Virgin America': 17670, 'Southwest Airlines': 1352552, 'Mesa Airline': 215138,
        'Republic Airways': 316090, 'American Airlines': 916818, 'Delta Airlines': 949283}
